export const ICONS = {
    logo: 'palette',
    search: 'search',
    trending: 'trending_up',
    chevronUp: 'expand_less',
    chevronDown: 'expand_more',
    chevronLeft: 'chevron_left',
    chevronRight: 'chevron_right',
    star: 'star',
    starHalf: 'star_half',
    heart: 'favorite',
    cart: 'shopping_cart',
    eye: 'visibility',
    clock: 'history',
    comment: 'chat_bubble',
    call: 'call',
    bookmark: 'bookmark',
    sun: 'light_mode',
    moon: 'dark_mode',
    filter: 'tune',
    close: 'close',
    info: 'info',
    checkCircle: 'check_circle',
    user: 'account_circle',
    trash: 'delete',
    add: 'person_add',
    check: 'check',
    edit: 'edit',
    // FIX: Added 'send' icon for chat functionality.
    send: 'send',
    sell: 'storefront',
    upload: 'upload_file',
    auto_awesome: 'auto_awesome',

};